<?php
require_once dirname( dirname( dirname( __FILE__ ) ) ) . '\classes\extendedstandardclass.php';

class Dummy_ExtendedStandardClass extends ExtendedStandardClass {}

/**
 * Test class for Github_Requester.
 * Generated by PHPUnit on 2013-05-24 at 22:50:19.
 */
class Github_RequesterTest extends \WP_UnitTestCase
{
	/**
	 * @var ExtendedStandardClass
	 */
	protected $object;

	/**
	 * ID for tests
	 * @var string
	 */
	protected $id = 'foobarbaz';

    /**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Dummy_ExtendedStandardClass();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {}

	/**
	 * @covers ExtendedStandardClass::set_id()
	 */
	public function testSet_id() {

		$this->object->set_id( $this->id );

		$result = ( Dummy_ExtendedStandardClass::$id === $this->id );

		$this->assertTrue( $result );

	}

	/**
	 * @covers ExtendedStandardClass::__set()
	 */
	public function testSet() {

		$bar = 'bar';
		$var = 'baz';

		$this->object->set_id( $this->id );
		$this->object->bar = $var;

		// test static direkt
		$this->assertTrue( isset( Dummy_ExtendedStandardClass::$data ) );

		// test OO
		$this->assertTrue( property_exists( $this->object, 'data' ) );

	}

}